import Head from "next/head";
import Table from "./components/Table";

const apiUrl =
  "https://api.coingecko.com/api/v3/coins/markets?vs_currency=eur&category=layer-1&order=market_cap_desc&per_page=10&page=1&sparkline=false&locale=en";

export const getStaticProps = async () => {
  const response = await fetch(apiUrl);
  const data = await response.json();
  return {
    props: {
      data,
    },
  };
};

export default function Home({ data }) {
  // console.log(data);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link href="/dist/output.css" rel="stylesheet" /> */}
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <table className="table-auto">
          <thead>
            <tr>
              <th>Song</th>
              <th>Artist</th>
              <th>Year</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>The Sliding Mr. Bones (Next Stop, Pottersville)</td>
              <td>Malcolm Lockyer</td>
              <td>1961</td>
            </tr>
            <tr>
              <td>Witchy Woman</td>
              <td>The Eagles</td>
              <td>1972</td>
            </tr>
            <tr>
              <td>Shining Star</td>
              <td>Earth, Wind, and Fire</td>
              <td>1975</td>
            </tr>
          </tbody>
        </table>
        <Table data={data} />
      </main>
    </>
  );
}
